### ISSUE TITLE
Redmine 0.9 error on migrate_plugins

### ISSUE THREAD

**Issue by GrantMcHerron** [dalyons/redmine-todos-scrum-plugin#18]
Hi there,

I've installed todos on a Redmine 0.9 system that was migrated from 0.8 (eg: not a fresh 0.9 install from scratch).

I've set up the todos plugin (with the correctly named directory) but when I go to run the migrate_plugins command, rake aborts saying "Child already added!" (see trace below)

What have I done wrong?

Cheers,

Grant

---

*\* Invoke db:migrate_plugins (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Child already added
/opt/redmine-0.9/lib/redmine/menu_manager.rb:77:in `add'
/opt/redmine-0.9/lib/redmine/menu_manager.rb:358:in`push'
/opt/redmine-0.9/lib/redmine/plugin.rb:178:in `menu'
/opt/redmine-0.9/vendor/plugins/redmine-todos-plugin/init.rb:57:in`evaluate_init_rb'
/opt/redmine-0.9/lib/redmine/plugin.rb:67:in `instance_eval'
/opt/redmine-0.9/lib/redmine/plugin.rb:67:in`register'
/opt/redmine-0.9/vendor/plugins/redmine-todos-plugin/init.rb:33:in `evaluate_init_rb'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin.rb:158:in`evaluate_init_rb'
/opt/redmine-0.9/vendor/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin.rb:154:in`evaluate_init_rb'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin.rb:48:in `load'
/opt/redmine-0.9/config/../vendor/plugins/engines/lib/engines/plugin.rb:44:in`load'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:38:in `load_plugins'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:37:in`each'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:37:in `load_plugins'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/initializer.rb:369:in`load_plugins'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/initializer.rb:165:in `process'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/initializer.rb:113:in`send'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/initializer.rb:113:in `run'
/opt/redmine-0.9/config/environment.rb:20
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
/opt/redmine-0.9/vendor/rails/activesupport/lib/active_support/dependencies.rb:158:in`require'
/opt/redmine-0.9/vendor/rails/railties/lib/tasks/misc.rake:4
/usr/lib/ruby/1.8/rake.rb:636:in `call'
/usr/lib/ruby/1.8/rake.rb:636:in`execute'
/usr/lib/ruby/1.8/rake.rb:631:in `each'
/usr/lib/ruby/1.8/rake.rb:631:in`execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in`invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in `each'
/usr/lib/ruby/1.8/rake.rb:604:in`invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in`invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in `each'
/usr/lib/ruby/1.8/rake.rb:2029:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
##

**Comment by GrantMcHerron** [comment]
Ooops - sorry - here's the trace in better format :)

```
** Invoke db:migrate_plugins (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Child already added
/opt/redmine-0.9/lib/redmine/menu_manager.rb:77:in `add'
/opt/redmine-0.9/lib/redmine/menu_manager.rb:358:in `push'
/opt/redmine-0.9/lib/redmine/plugin.rb:178:in `menu'
/opt/redmine-0.9/vendor/plugins/redmine-todos-plugin/init.rb:57:in `evaluate_init_rb'
/opt/redmine-0.9/lib/redmine/plugin.rb:67:in `instance_eval'
/opt/redmine-0.9/lib/redmine/plugin.rb:67:in `register'
/opt/redmine-0.9/vendor/plugins/redmine-todos-plugin/init.rb:33:in `evaluate_init_rb'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin.rb:158:in `evaluate_init_rb'
/opt/redmine-0.9/vendor/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin.rb:154:in `evaluate_init_rb'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin.rb:48:in `load'
/opt/redmine-0.9/config/../vendor/plugins/engines/lib/engines/plugin.rb:44:in `load'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:38:in `load_plugins'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:37:in `each'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/rails/plugin/loader.rb:37:in `load_plugins'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/initializer.rb:369:in `load_plugins'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/initializer.rb:165:in `process'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/initializer.rb:113:in `send'
/opt/redmine-0.9/config/../vendor/rails/railties/lib/initializer.rb:113:in `run'
/opt/redmine-0.9/config/environment.rb:20
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
/opt/redmine-0.9/vendor/rails/activesupport/lib/active_support/dependencies.rb:158:in `require'
/opt/redmine-0.9/vendor/rails/railties/lib/tasks/misc.rake:4
/usr/lib/ruby/1.8/rake.rb:636:in `call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/usr/lib/ruby/1.8/rake.rb:631:in `each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in `each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in `each'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
```

**Comment by dalyons** [comment]
sorry about the late reply - ive been away on holidays :)

Are you still having the problem? If so does this look like it might apply?
http://www.redmine.org/boards/3/topics/11612?r=11991

**Comment by GrantMcHerron** [comment]
I just tried it again with  the latest version and all is fine - thanks :)

NOTE: I ran the git clone today so I should have 0.4.1 but under Administration->Plugins, it shows version 0.0.3.9. Is 0.4.1 still under test and not available by git clone or is the version number in the code incorrect?

**Comment by GrantMcHerron** [comment]
By the way, the topic you linked to helped solve a problem I had with another plugin, so between that and your updated version, plugins are working again. Thanks heaps :)
