### ISSUE TITLE
ActionView::TemplateError on Redmine0.9.3

### ISSUE THREAD

**Issue by akiko-pusu** [dalyons/redmine-todos-scrum-plugin#23]
Hello, I've just installed todos plugin on my Redmine0.9.3.
And I saw following error mesage...

<pre>

ActionView::TemplateError (No plugin called 'redmine_todos_plugin' - please use the full n
ame of a loaded plugin.) on line #2 of vendor/plugins/redmine_todos/app/views/mytodos/inde
x.html.erb:
1: <% content_for :header_tags do %>
2:     <%= stylesheet_link_tag 'todos', :plugin => 'redmine_todos_plugin' %>
3:     <%= stylesheet_link_tag 'todos_print', :plugin => 'redmine_todos_plugin', :media =>
 'print' %>
4: <% end %>

</pre>

Though I don't have much knowledge about ROR and Redmien, I modified all view files following above error message. (Just replace "redmine_todos_plugin" to "redmine_todos")

I'm not sure this workaround is collect or not and not sure this problem is happen in my environment only, but now I can handle todos without problem.

 I'm glad this post could be of any help to you.

**Comment by akiko-pusu** [comment]
Sorry, I did not read README well and I could use plugin without any changes after renaming plugin's directory as "redmine_todos_plugin".

But after that, I saw some storange action.
When I tried to create ticket, internal server error was happened.

In addition to this, some user (without create issue privilege) accesses to a project which uses todo modules, "Create Ticket" tab is shown.

Also any user who can create ticket, can't submit new issue because of  ActionView::TemplateError.

<pre>
Rendering template within layouts/base
Rendering issues/show.rhtml

ActionView::TemplateError (Can only render or redirect once per action) on line #17 of app/views/layouts/base.rhtml:
14:       body {behavior: url(<%= stylesheet_path "csshover.htc" %>);}
15:     </style>
16: <![endif]-->
17: <%= call_hook :view_layouts_base_html_head %>
18: 
19: <%= yield :header_tags -%>
20: </head>

    lib/redmine/hook.rb:113:in `send'
    lib/redmine/hook.rb:113:in `view_layouts_base_html_head'
    lib/redmine/hook.rb:63:in `send'
    lib/redmine/hook.rb:63:in `call_hook'
    lib/redmine/hook.rb:63:in `each'
    lib/redmine/hook.rb:63:in `call_hook'
    lib/redmine/hook.rb:60:in `call_hook'
    lib/redmine/hook.rb:144:in `call_hook'
    app/views/layouts/base.rhtml:17:in `_run_rhtml_app47views47layouts47base46rhtml'
    app/controllers/issues_controller.rb:117:in `show_without_todo'
    app/controllers/issues_controller.rb:116:in `show_without_todo'



</pre>

**Comment by dalyons** [comment]
Yeah, the directory has to be named just right, its a limitation of the plugin engine :)

For the second issue could you tell me if you set up permissions for the todos plugin _after_ renaming the directory, before trying to create a new issue?

**Comment by xyz37** [comment]
I got an error too. and my symptom is same suama
my error error messages...

Processing TodosController#create (for 127.0.0.1 at 2010-03-17 20:28:01) [POST]
  Parameters: {"commit"=>"할일 만들\352\270\260", "project_id"=>"isetda", "action"=>"create", "authenticity_token"=>"/cH5r+KlcVCZA6HvaLhHmyus+62uxpOxh1EZClMSZDA=", "controller"=>"todos", "todo"=>{"issue_id"=>"56", "text"=>"", "assigned_to_id"=>"3", "parent_id"=>"", "due"=>""}}
Rendering template within layouts/base
Rendering todos/index

ActionView::TemplateError (undefined method `sort' for nil:NilClass) on line #6 of vendor/plugins/redmine_todos_plugin/app/views/todos/_root_todos.html.erb:
3: <% raise unless parent_object %>
4: 
5:     <ul class="todos root" id="<%= TodosController::UL_ID + 'root' %><%='not-editable' unless editable %>">
6:       <% for todo in todos.sort{|a,b| a.position <=> b.position} %>
7:           <%= render :partial => 'todos/todo_li', :locals => { :todo => todo, :editable => editable }%>
8:       <% end %>
9:     </ul>

```
vendor/plugins/redmine_todos_plugin/app/views/todos/_root_todos.html.erb:6
vendor/plugins/redmine_todos_plugin/app/views/todos/index.html.erb:19
vendor/plugins/redmine_todos_plugin/app/controllers/todos_controller.rb:109:in `create'
D:/CI/Ruby/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
D:/CI/Ruby/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:162:in `start'
D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:95:in `start'
D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:92:in `each'
D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:92:in `start'
D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:23:in `start'
D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering rescues/layout (internal_server_error)

---

My enviromments are
Windows 2003 Server Standard SP2
Redmine 0.9.3
and
About your application's environment
Ruby version              1.8.7 (i386-mingw32)
RubyGems version          1.3.5
Rack version              1.0
Rails version             2.3.5
Active Record version     2.3.5
Active Resource version   2.3.5
Action Mailer version     2.3.5
Active Support version    2.3.5
Application root          D:/CI/Redmine
Environment               production
Database adapter          mysql
Database schema version   20100221100219

About your Redmine plugins
Redmine Todo Lists plugin    0.0.3.9
Redmine Bugcloud plugin      0.0.2.1
Issues XLS export            0.0.3
Redmine Code Review plugin   0.2.9.3
Charts Plugin                0.0.14

**Comment by pageworthy** [comment]
I get the same template error (second error in original post above)  I did the original checkout to a fresh 0.9.3 install and then added permissions to each role. When I visit a issue detail page I get the following error:

ActionView::TemplateError (Can only render or redirect once per action) on line #70 of app/views/layouts/base.rhtml:
67:     Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2010 Jean-Philippe Lang
68: </div>
69: </div>
70: <%= call_hook :view_layouts_base_body_bottom %>
71: </body>
72: </html>

```
lib/redmine/hook.rb:113:in `send'  
lib/redmine/hook.rb:113:in `view_layouts_base_body_bottom'
lib/redmine/hook.rb:63:in `send'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:144:in `call_hook'
app/views/layouts/base.rhtml:70:in `_run_rhtml_app47views47layouts47base46rhtml'
app/controllers/issues_controller.rb:117:in `show_without_todo'
app/controllers/issues_controller.rb:116:in `show_without_todo'
passenger (2.2.8) lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
```

My only fix was to uninstall unfortunately.

**Comment by pageworthy** [comment]
Made an error above, my redmine version is actually 0.9.4

**Comment by dalyons** [comment]
Sorry about the delay.

can you do a git pull on the plugin and try again?
I couldnt reproduce your bug locally, but i think ive figured out what was causing it.
