### ISSUE TITLE
ActionController::DoubleRenderError in Issues#show (commit 4b00d5e)

### ISSUE THREAD

**Issue by hooke** [dalyons/redmine-todos-scrum-plugin#27]
I've installed the redmine-todos-scrum-plugin from this repository.
The last commit is [4b00d5e](http://github.com/dalyons/redmine-todos-scrum-plugin/commit/4b00d5e11cac3d24212dca92d6d2179e265b4337).

ToDos work OK. I created few of them in one of projects, used nested todos, and even linked one of todos to an issue. Then a problem appeared: When I try to open any issue in any of the projects, the following error appears:

<pre>
ActionController::DoubleRenderError in Issues#show

Showing app/views/layouts/base.rhtml where line #17 raised:

Can only render or redirect once per action

Extracted source (around line #17):

14:       body {behavior: url(<%= stylesheet_path "csshover.htc" %>);}
15:     </style>
16: <![endif]-->
17: <%= call_hook :view_layouts_base_html_head %>
18: 
19: <%= yield :header_tags -%>
20: </head>

RAILS_ROOT: /home/hooke/redmine-0.9.3
Application Trace | Framework Trace | Full Trace

/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:900:in `render_without_benchmark'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:995:in `render_to_string'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:113:in `send'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:113:in `view_layouts_base_html_head'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:63:in `send'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:63:in `call_hook'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:63:in `each'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:63:in `call_hook'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:60:in `call_hook'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:144:in `call_hook'
/home/hooke/redmine-0.9.3/app/views/layouts/base.rhtml:17:in `_run_rhtml_app47views47layouts47base46rhtml'
/home/hooke/redmine-0.9.3/app/controllers/issues_controller.rb:117:in `show_without_todo'
/home/hooke/redmine-0.9.3/app/controllers/issues_controller.rb:116:in `show_without_todo'

/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:900:in `render_without_benchmark'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:995:in `render_to_string'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/object/misc.rb:39:in `returning'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `send'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:306:in `with_template'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:30:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/template.rb:205:in `render_template'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:265:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:352:in `_render_with_layout'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:262:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1250:in `render_for_file'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:945:in `render_without_benchmark'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:135:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:135:in `custom'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:179:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:179:in `respond'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:173:in `each'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:173:in `respond'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:107:in `respond_to'
/home/hooke/redmine-0.9.3/vendor/plugins/redmine_todos_plugin/lib/todo_issues_controller_patch.rb:43:in `show'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1331:in `send'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1331:in `perform_action_without_filters'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:617:in `call_filters'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/flash.rb:146:in `perform_action'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `send'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `process_without_filters'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:606:in `process'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:391:in `process'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:386:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:437:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:87:in `dispatch'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:121:in `_call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:9:in `cache'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:28:in `call'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/string_coercion.rb:25:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/head.rb:9:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/methodoverride.rb:24:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/params_parser.rb:15:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/session/cookie_store.rb:93:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/failsafe.rb:26:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `synchronize'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:106:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:46:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `each'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/content_length.rb:13:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/handler/webrick.rb:50:in `service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/handler/webrick.rb:14:in `run'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
script/server:3

/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:900:in `render_without_benchmark'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:995:in `render_to_string'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:113:in `send'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:113:in `view_layouts_base_html_head'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:63:in `send'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:63:in `call_hook'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:63:in `each'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:63:in `call_hook'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/object/misc.rb:39:in `returning'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:60:in `call_hook'
/home/hooke/redmine-0.9.3/lib/redmine/hook.rb:144:in `call_hook'
/home/hooke/redmine-0.9.3/app/views/layouts/base.rhtml:17:in `_run_rhtml_app47views47layouts47base46rhtml'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `send'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:306:in `with_template'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:30:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/template.rb:205:in `render_template'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:265:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:352:in `_render_with_layout'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:262:in `render'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1250:in `render_for_file'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:945:in `render_without_benchmark'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render'
/home/hooke/redmine-0.9.3/app/controllers/issues_controller.rb:117:in `show_without_todo'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:135:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:135:in `custom'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:179:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:179:in `respond'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:173:in `each'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:173:in `respond'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/mime_responds.rb:107:in `respond_to'
/home/hooke/redmine-0.9.3/app/controllers/issues_controller.rb:116:in `show_without_todo'
/home/hooke/redmine-0.9.3/vendor/plugins/redmine_todos_plugin/lib/todo_issues_controller_patch.rb:43:in `show'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1331:in `send'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1331:in `perform_action_without_filters'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:617:in `call_filters'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/home/hooke/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/flash.rb:146:in `perform_action'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `send'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `process_without_filters'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:606:in `process'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:391:in `process'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:386:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:437:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:87:in `dispatch'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:121:in `_call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:9:in `cache'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:28:in `call'
/home/hooke/.gem/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/string_coercion.rb:25:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/head.rb:9:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/methodoverride.rb:24:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/params_parser.rb:15:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/session/cookie_store.rb:93:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/failsafe.rb:26:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `synchronize'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/home/hooke/.gem/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:106:in `call'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/rails/rack/static.rb:31:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:46:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `each'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `call'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/rails/rack/log_tailer.rb:17:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/content_length.rb:13:in `call'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/handler/webrick.rb:50:in `service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
/home/hooke/.gem/ruby/1.8/gems/rack-1.0.1/lib/rack/handler/webrick.rb:14:in `run'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:111
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
script/server:3

Request

Parameters:

{"id"=>"3"}

Show session dump

--- 

Response

Headers:

{"Content-Type"=>"",
 "Cache-Control"=>"no-cache"}
</pre>

My environment:
Ubuntu 9.10
Redmine 0.9.3.stable.3668 (MySQL)
About your application's environment  
Ruby version              1.8.7 (i486-linux)  
RubyGems version          1.3.5  
Rack version              1.0  
Rails version             2.3.5  
Active Record version     2.3.5  
Active Resource version   2.3.5
Action Mailer version     2.3.5
Active Support version    2.3.5
Application root          /home/hooke/redmine-0.9.3
Environment               development
Database adapter          mysql
Database schema version   20100221100219

About your Redmine plugins
Rate Plugin                 0.1.0
Budget                      0.2.0
Redmine Blogs plugin        0.1.0
Redmine Milestones plugin   0.1
Redmine Todo Lists plugin   0.0.3.9

Redmine is run in production mode.

After I moved plugin's folder outside of vendor/plugins, and restarted webserver, I can open issue without a problem.

Could you please fix it? 

If you need more information, please ask!

**Comment by dalyons** [comment]
Sorry about the delay.

can you do a git pull on the plugin and try again?
I couldnt reproduce your bug locally, but i think ive figured out what was causing it.
