### ISSUE TITLE
Getting - Internal Error 

### ISSUE THREAD

**Issue by kscraja** [dalyons/redmine-todos-scrum-plugin#35]
Hi, 
very recently I installed redmine(0.9.3) + todos plugin.  on ubuntu 10.04 (64 bit). 
I am getting the following error.

internal error
an error occurred on the page you were trying to access.
if you continue to experience problems please contact your redMine administrator for assistance.
I googled for a while but not able to find a fix for this problem.
Need your help

redmine install info:
activesupport (3.0.1)
arel (1.0.1)
builder (2.1.2)
bundler (1.0.3)
erubis (2.6.6)
i18n (0.4.1)
mail (2.2.7)
mime-types (1.16)
mysql (2.8.1)
polyglot (0.3.1)
rack (1.2.1, 1.0.1)
rack-mount (0.6.13)
rack-test (0.5.6)
rails (3.0.1)
railties (3.0.1)
rake (0.8.7)
thor (0.14.3)
treetop (1.4.8)
tzinfo (0.3.23)

**Comment by mreyzlin-spotuse** [comment]
Same here.
Ubuntu 10.04, Redmine 1.1.

Internal error when going to the "My Todos" link.

**Comment by dalyons** [comment]
can either of you please post some log data that shows the error?

The logs for a rails project are found in REDMINE_PATH/log/production.log (or development.log)

**Comment by findup** [comment]
Same here.
Redmine 1.1.

## [REDMINE_PATH/log/production.log]

Processing MytodosController#index (for xxx.xxx.xxx.xxx at 2011-03-04 16:32:43) [GET]
  Parameters: {"action"=>"index", "controller"=>"mytodos"}
Rendering template within layouts/base
Rendering mytodos/index

ActionView::TemplateError (No plugin called 'redmine_todos_plugin' - please use the full name of a loaded plugin.) on line #2 of vendor/plugins/dalyons-redmine-todos-scrum-plugin-06cfd76/app/views/mytodos/index.html.erb:
1: <% content_for :header_tags do %>
2:     <%= stylesheet_link_tag 'todos', :plugin => 'redmine_todos_plugin' %>
3:     <%= stylesheet_link_tag 'todos_print', :plugin => 'redmine_todos_plugin', :media => 'print' %>
4: <% end %>
5:

```
vendor/plugins/dalyons-redmine-todos-scrum-plugin-06cfd76/app/views/mytodos/index.html.erb:2
app/helpers/application_helper.rb:856:in `content_for'
vendor/plugins/dalyons-redmine-todos-scrum-plugin-06cfd76/app/views/mytodos/index.html.erb:1
passenger (3.0.3) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.3) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
passenger (3.0.3) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.3) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
passenger (3.0.3) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
passenger (3.0.3) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
passenger (3.0.3) lib/phusion_passenger/utils.rb:479:in `safe_fork'
passenger (3.0.3) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
passenger (3.0.3) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.3) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.3) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.3) lib/phusion_passenger/abstract_server.rb:180:in `start'
passenger (3.0.3) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
passenger (3.0.3) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
passenger (3.0.3) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.3) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
passenger (3.0.3) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
passenger (3.0.3) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.3) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
passenger (3.0.3) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
passenger (3.0.3) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
passenger (3.0.3) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.3) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.3) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.3) helper-scripts/passenger-spawn-server:99
```

**Comment by findup** [comment]
I solved.
Install plugin directory to "REDMINE_PATH/vendor/plugins/redmine_todo_plugin".
Not "REDMINE_PATH/vendor/plugins/dalyons-redmine-todos-scrum-plugin".

**Comment by ghost** [comment]
Renaming the directory doesn't improve the error..
