### ISSUE TITLE
Crash with Redmine 0.80

### ISSUE THREAD

**Issue by turf00** [dalyons/redmine-todos-scrum-plugin#5]
Hello,

I downloaded the plugin from the downloads link at the top and this turned out to 0.0.3.6.  This was a great release but I needed the functionality to see the todos on the issue page so I got the latest version out of the main tree.  

This was version 0.0.4.0

This version does not work with my Redmine I include the error below for your info.  This is the same error as posted here on the forums: http://www.redmine.org/boards/3/topics/4070#message-9036

Processing TodosController#index (for 10.28.66.134 at 2009-10-11 10:58:06) [GET]
  Session ID: 26ce628a2ba174a5c3edf3e6a44e83a7
  Parameters: {"project_id"=>"leedsdbmigration", "action"=>"index", "controller"=>"todos"}
Rendering template within layouts/base
Rendering todos/index

ActionView::TemplateError (wrong number of arguments (2 for 1)) on line #25 of vendor/plugins/redmine_todos_plugin/app/views/todos/_todo.html.erb:
22:           :html => {:class => todo_class} 
23:          )
24:     %><%= link_to_remote( image_tag('add.png', :title => l(:todo_add_child_tooltip)), 
25:       :url => new_polymorphic_url( [parent_object,:todo], :parent_id => todo, :issue_id => todo_issue), :method => :get,
26:  
27:       #{ :controller => "#{'projects/' + todo.project.identifier.to_s + '/' if todo.project}#{'issues/' + todo_issue.to_s + '/' if todo_issue}#{todos_controller}/#{todo.id}",     :action => 'new' },
28:       :html => {:class => 'icon-new'}, 

```
vendor/plugins/redmine_todos_plugin/app/views/todos/_todo.html.erb:25:in `new_polymorphic_url'
vendor/plugins/redmine_todos_plugin/app/views/todos/_todo.html.erb:25:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47_todo46html46erb'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `send'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `execute'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `send'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `render'
vendor/rails/actionpack/lib/action_view/partial_template.rb:20:in `render'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:30:in `benchmark'
vendor/rails/actionpack/lib/action_view/partial_template.rb:19:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:22:in `render_template'
vendor/rails/actionpack/lib/action_view/partials.rb:110:in `render_partial'
vendor/rails/actionpack/lib/action_view/base.rb:277:in `render'
vendor/plugins/redmine_todos_plugin/app/views/todos/_todo_li.html.erb:2:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47_todo_li46html46erb'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `send'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `execute'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `send'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `render'
vendor/rails/actionpack/lib/action_view/partial_template.rb:20:in `render'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:30:in `benchmark'
vendor/rails/actionpack/lib/action_view/partial_template.rb:19:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:22:in `render_template'
vendor/rails/actionpack/lib/action_view/partials.rb:110:in `render_partial'
vendor/rails/actionpack/lib/action_view/base.rb:277:in `render'
vendor/plugins/redmine_todos_plugin/app/views/todos/_root_todos.html.erb:7:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47_root_todos46html46erb'
vendor/plugins/redmine_todos_plugin/app/views/todos/_root_todos.html.erb:6:in `each'
vendor/plugins/redmine_todos_plugin/app/views/todos/_root_todos.html.erb:6:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47_root_todos46html46erb'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `send'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `execute'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `send'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `render'
vendor/rails/actionpack/lib/action_view/partial_template.rb:20:in `render'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:30:in `benchmark'
vendor/rails/actionpack/lib/action_view/partial_template.rb:19:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:22:in `render_template'
vendor/rails/actionpack/lib/action_view/partials.rb:110:in `render_partial'
vendor/rails/actionpack/lib/action_view/base.rb:277:in `render'
vendor/plugins/redmine_todos_plugin/app/views/todos/index.html.erb:19:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47index46html46erb'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `send'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `execute'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `send'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:35:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:22:in `render_template'
vendor/rails/actionpack/lib/action_view/base.rb:248:in `render_file'
vendor/rails/actionpack/lib/action_controller/base.rb:1112:in `render_for_file'
vendor/rails/actionpack/lib/action_controller/base.rb:845:in `render_with_no_layout'
vendor/rails/actionpack/lib/action_controller/layout.rb:251:in `render_without_benchmark'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:51:in `render'
vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:8:in `realtime'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:51:in `render'
vendor/rails/actionpack/lib/action_controller/base.rb:1161:in `default_render'
vendor/rails/actionpack/lib/action_controller/base.rb:1167:in `perform_action_without_filters'
vendor/rails/actionpack/lib/action_controller/filters.rb:579:in `call_filters'
vendor/rails/actionpack/lib/action_controller/filters.rb:572:in `perform_action_without_benchmark'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
c:/Program Files/TestSrv/ruby/lib/ruby/1.8/benchmark.rb:293:in `measure'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
vendor/rails/actionpack/lib/action_controller/rescue.rb:201:in `perform_action_without_caching'
vendor/rails/actionpack/lib/action_controller/caching/sql_cache.rb:13:in `perform_action'
vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:33:in `cache'
vendor/rails/activerecord/lib/active_record/query_cache.rb:8:in `cache'
vendor/rails/actionpack/lib/action_controller/caching/sql_cache.rb:12:in `perform_action'
vendor/rails/actionpack/lib/action_controller/base.rb:529:in `send'
vendor/rails/actionpack/lib/action_controller/base.rb:529:in `process_without_filters'
vendor/rails/actionpack/lib/action_controller/filters.rb:568:in `process_without_session_management_support'
vendor/rails/actionpack/lib/action_controller/session_management.rb:130:in `process'
vendor/rails/actionpack/lib/action_controller/base.rb:389:in `process'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:149:in `handle_request'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:107:in `dispatch'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:104:in `synchronize'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:104:in `dispatch'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:120:in `dispatch_cgi'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:35:in `dispatch'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel/rails.rb:76:in `process'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel/rails.rb:74:in `synchronize'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel/rails.rb:74:in `process'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:159:in `process_client'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:158:in `each'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:158:in `process_client'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:285:in `run'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:285:in `initialize'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:285:in `new'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:285:in `run'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:268:in `initialize'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:268:in `new'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel.rb:268:in `run'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel/configurator.rb:282:in `run'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel/configurator.rb:281:in `each'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel/configurator.rb:281:in `run'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/bin/mongrel_rails:128:in `run'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/lib/mongrel/command.rb:212:in `run'
c:/Program Files/TestSrv/ruby/lib/ruby/gems/1.8/gems/mongrel-1.1.5-x86-mswin32-60/bin/mongrel_rails:281
c:/Program Files/TestSrv/ruby/bin/mongrel_rails:16:in `load'
c:/Program Files/TestSrv/ruby/bin/mongrel_rails:16
```

Rendering C:/Program Files/TestSrv/ProjManage/redmine/public/500.html (500 Internal Server Error)

**Comment by dalyons** [comment]
That arguments error is caused if your rails version is too old.
0.0.4 requires at least Rails 2.2.1 to run.

I have updated the README to state the requirements.

I see you are running on windows - I know that rails for windows is usually a few versions behind. If you absolutely cannot upgrade, I can see if I can find a the latest revision you can run - however you will miss out on all post-0.3.8 functionality.

**Comment by turf00** [comment]
Can we run Redmine 0.8.5 with Rails 2.2.1?

It is marked against 2.1.2 on the Install Wiki on the Redmine site.  I do not mind upgrading Rails if we can run the standard releases.

Thanks for the reponse though, very useful plugin!

**Comment by dalyons** [comment]
I'm pretty sure 0.8.5 runs fine on 2.2.1, but you'll have to test it out fully for your self! 
Im working on a way to backport the missing url functionality to make it work in 2.1.2.

**Comment by wojtha** [comment]
For me Redmine (0.8.6, 0.8.7) doesn't run on Rails 2.2.x on Windows platform (Vista 32bit). The Rails 2.1.2 is only Rails version which works for me.

**Comment by peernohell** [comment]
juste test redmine 0.8.7 with rails 2.2.3 on linux and it's doesn't work :/

**Comment by dalyons** [comment]
@wojtha, I am sorry, I dont really know waht to do about your issue on windows. Redmine 0.9.x is out, and it requires rails 2.3.5, so you are going to have to upgrade your rails sooner or later. Perhaps run a VM? rails on windows is not very supported
