### ISSUE TITLE
it does not work under redmine 1.2.1

### ISSUE THREAD

**Issue by blurmonk** [dalyons/redmine-todos-scrum-plugin#51]
Hi 
After I install this I am getting "internal error" when I click on the todo tab.

thanks

**Comment by sukima** [comment]
Here is the putput:

```
Processing MytodosController#index (for 10.0.163.152 at 2012-03-26 15:45:01) [GET]
  Parameters: {"action"=>"index", "controller"=>"mytodos"}
Rendering template within layouts/base
Rendering mytodos/index

ActionView::TemplateError (No plugin called 'redmine_todos_plugin' - please use the full name of a loaded plugin.) on line #2 of vendor/plugins/redmine-todos-scrum-plugin/app/views/mytodos/index.html.erb:
1: <% content_for :header_tags do %>
2:     <%= stylesheet_link_tag 'todos', :plugin => 'redmine_todos_plugin' %>
3:     <%= stylesheet_link_tag 'todos_print', :plugin => 'redmine_todos_plugin', :media => 'print' %>
4: <% end %>
5: 

    vendor/plugins/redmine-todos-scrum-plugin/app/views/mytodos/index.html.erb:2
    app/helpers/application_helper.rb:873:in `content_for'
    vendor/plugins/redmine-todos-scrum-plugin/app/views/mytodos/index.html.erb:1
    passenger (3.0.11) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
    passenger (3.0.11) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
    passenger (3.0.11) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
    passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
    passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
    passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
    passenger (3.0.11) lib/phusion_passenger/utils.rb:479:in `safe_fork'
    passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
    passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
    passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
    passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
    passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:180:in `start'
    passenger (3.0.11) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
    passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
    passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
    passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
    passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
    passenger (3.0.11) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
    passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
    passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
    passenger (3.0.11) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
    passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
    passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
    passenger (3.0.11) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
    passenger (3.0.11) helper-scripts/passenger-spawn-server:99

Rendering /var/www-apps/issues/releases/20120326193035/public/500.html (500 Internal Server Error)
```
