### ISSUE TITLE
Not compatible with Redmine 2.0.0

### ISSUE THREAD

**Issue by urjitrajgor** [dalyons/redmine-todos-scrum-plugin#57]
I  try to install this plugin in redmine 2.0.0. 
when I try to run plugin migration I get following error.

workspace/redmine2$ rake redmine:plugins:migrate --trace

*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
no such file to load -- dispatcher
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
/home/likewise-open/RADIXLOCAL/urjit.rajgor/workspace/redmine2/plugins/todos_scrum/init.rb:7
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
/home/likewise-open/RADIXLOCAL/urjit.rajgor/workspace/redmine2/lib/redmine/plugin.rb:129:in `load'
/home/likewise-open/RADIXLOCAL/urjit.rajgor/workspace/redmine2/lib/redmine/plugin.rb:120:in`each'
/home/likewise-open/RADIXLOCAL/urjit.rajgor/workspace/redmine2/lib/redmine/plugin.rb:120:in `load'
/home/likewise-open/RADIXLOCAL/urjit.rajgor/workspace/redmine2/config/initializers/30-redmine.rb:13
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in`load'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in`load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/engine.rb:588
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/engine.rb:587:in`each'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/engine.rb:587
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:30:in`run'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:55:in `run_initializers'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:54:in`each'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/application.rb:136:in`initialize!'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `send'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in`method_missing'
/home/likewise-open/RADIXLOCAL/urjit.rajgor/workspace/redmine2/config/environment.rb:14
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/application.rb:103:in `require'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/application.rb:103:in`require_environment!'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.3/lib/rails/application.rb:292
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:176:in`invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:144:in`invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:88:in`top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/usr/bin/rake:19:in`load'
/usr/bin/rake:19

This is because of redmine 2.0.0 is in rails 3 and this plugin is in rails 2.
Please suggest me some patches made in this plugin.

Thanks.

**Comment by cforce** [comment]
Does this fork work for you ?
https://github.com/ourstage/redmine-todos-scrum-plugin/

**Comment by mrgcohen** [comment]
no this does not work

**Comment by ilya-il** [comment]
David, do you plan to upgrade plugin to Redmine 2.x? Your plugin is very usefull, but not compatible with Redmine 2.x
Thanks

**Comment by acrazylion** [comment]
Hello David.

After we update Redmine to Version 2.x the your plugin couldn't get installed again. 

We used this Plugin very intensively! Could you told us if you plan an update or tell us how to fix the problem with the update.

Thanks a lot for your response!

Greetings,
 Mike.

**Comment by cforce** [comment]
Please checkou follwiwung forks and check if they work for you. Both wants to be compatible with redmine 2.x

https://github.com/sawan1990/redmine-todos-scrum-plugin.git
https://github.com/hshield/redmine-todos-scrum-plugin.git

**Comment by cforce** [comment]
Don't forget to migrate the plugin, maybe its necesarry

**Comment by acrazylion** [comment]
Thanks a lot. The version from hshield runs fine.
It would be a good idea to add this plugin to the redmine plugin page.  its sadly not listed.

**Comment by cforce** [comment]
It's always a good idea to check the forks (change notes) in the network view. See "Button" network above

https://github.com/dalyons/redmine-todos-scrum-plugin/network

**Comment by cforce** [comment]
Did you also test https://github.com/sawan1990/redmine-todos-scrum-plugin.git  ??
 It looks even more mainatained tahn hshields fork
