### ISSUE TITLE
ActionView::TemplateError (wrong number of arguments (2 for 1))

### ISSUE THREAD

**Issue by kunalashar** [dalyons/redmine-todos-scrum-plugin#8]
Redmine 0.8.5
Rails 2.2.2
Windows 2003

Installed latest version of redmine_todos_plugin in vendors/plugins. Migrated production DB. Restarted Redmine.

Get the following issue:

ActionView::TemplateError (wrong number of arguments (2 for 1)) on line #25 of vendor/plugins/redmine_todos_plugin/app/views/todos/_todo.html.erb:
22:           :html => {:class => todo_class} 
23:          )
24:     %><%= link_to_remote( image_tag('add.png', :title => l(:todo_add_child_tooltip)), 
25:       :url => new_polymorphic_url( [parent_object,:todo], :parent_id => todo, :issue_id => todo_issue), :method => :get,
26:  
27:       #{ :controller => "#{'projects/' + todo.project.identifier.to_s + '/' if todo.project}#{'issues/' + todo_issue.to_s + '/' if todo_issue}#{todos_controller}/#{todo.id}",     :action => 'new' },
28:       :html => {:class => 'icon-new'}, 

```
vendor/plugins/redmine_todos_plugin/app/views/todos/_todo.html.erb:25:in `new_polymorphic_url'
vendor/plugins/redmine_todos_plugin/app/views/todos/_todo.html.erb:25:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47_todo46html46erb'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `send'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `execute'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `send'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `render'
vendor/rails/actionpack/lib/action_view/partial_template.rb:20:in `render'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:30:in `benchmark'
vendor/rails/actionpack/lib/action_view/partial_template.rb:19:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:22:in `render_template'
vendor/rails/actionpack/lib/action_view/partials.rb:110:in `render_partial'
vendor/rails/actionpack/lib/action_view/base.rb:277:in `render'
vendor/plugins/redmine_todos_plugin/app/views/todos/_todo_li.html.erb:2:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47_todo_li46html46erb'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `send'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `execute'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `send'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `render'
vendor/rails/actionpack/lib/action_view/partial_template.rb:20:in `render'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:30:in `benchmark'
vendor/rails/actionpack/lib/action_view/partial_template.rb:19:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:22:in `render_template'
vendor/rails/actionpack/lib/action_view/partials.rb:110:in `render_partial'
vendor/rails/actionpack/lib/action_view/base.rb:277:in `render'
vendor/plugins/redmine_todos_plugin/app/views/todos/_root_todos.html.erb:7:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47_root_todos46html46erb'
vendor/plugins/redmine_todos_plugin/app/views/todos/_root_todos.html.erb:6:in `each'
vendor/plugins/redmine_todos_plugin/app/views/todos/_root_todos.html.erb:6:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47_root_todos46html46erb'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `send'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `execute'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `send'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `render'
vendor/rails/actionpack/lib/action_view/partial_template.rb:20:in `render'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:30:in `benchmark'
vendor/rails/actionpack/lib/action_view/partial_template.rb:19:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:22:in `render_template'
vendor/rails/actionpack/lib/action_view/partials.rb:110:in `render_partial'
vendor/rails/actionpack/lib/action_view/base.rb:277:in `render'
vendor/plugins/redmine_todos_plugin/app/views/todos/index.html.erb:19:in `_run_erb_47vendor47plugins47redmine_todos_plugin47app47views47todos47index46html46erb'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `send'
vendor/rails/actionpack/lib/action_view/base.rb:342:in `execute'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `send'
vendor/rails/actionpack/lib/action_view/template_handlers/compilable.rb:29:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:35:in `render'
vendor/rails/actionpack/lib/action_view/template.rb:22:in `render_template'
vendor/rails/actionpack/lib/action_view/base.rb:248:in `render_file'
vendor/rails/actionpack/lib/action_controller/base.rb:1112:in `render_for_file'
vendor/rails/actionpack/lib/action_controller/base.rb:845:in `render_with_no_layout'
vendor/rails/actionpack/lib/action_controller/layout.rb:251:in `render_without_benchmark'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:51:in `render'
vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:8:in `realtime'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:51:in `render'
vendor/rails/actionpack/lib/action_controller/base.rb:1161:in `default_render'
vendor/rails/actionpack/lib/action_controller/base.rb:1167:in `perform_action_without_filters'
vendor/rails/actionpack/lib/action_controller/filters.rb:579:in `call_filters'
vendor/rails/actionpack/lib/action_controller/filters.rb:572:in `perform_action_without_benchmark'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
D:/Tools/ruby/lib/ruby/1.8/benchmark.rb:293:in `measure'
vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
vendor/rails/actionpack/lib/action_controller/rescue.rb:201:in `perform_action_without_caching'
vendor/rails/actionpack/lib/action_controller/caching/sql_cache.rb:13:in `perform_action'
vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:33:in `cache'
vendor/rails/activerecord/lib/active_record/query_cache.rb:8:in `cache'
vendor/rails/actionpack/lib/action_controller/caching/sql_cache.rb:12:in `perform_action'
vendor/rails/actionpack/lib/action_controller/base.rb:529:in `send'
vendor/rails/actionpack/lib/action_controller/base.rb:529:in `process_without_filters'
vendor/rails/actionpack/lib/action_controller/filters.rb:568:in `process_without_session_management_support'
vendor/rails/actionpack/lib/action_controller/session_management.rb:130:in `process'
vendor/rails/actionpack/lib/action_controller/base.rb:389:in `process'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:149:in `handle_request'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:107:in `dispatch'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:104:in `synchronize'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:104:in `dispatch'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:120:in `dispatch_cgi'
vendor/rails/actionpack/lib/action_controller/dispatcher.rb:35:in `dispatch'
vendor/rails/railties/lib/webrick_server.rb:112:in `handle_dispatch'
vendor/rails/railties/lib/webrick_server.rb:78:in `service'
D:/Tools/ruby/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
D:/Tools/ruby/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:162:in `start'
D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:95:in `start'
D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:92:in `each'
D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:92:in `start'
D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:23:in `start'
D:/Tools/ruby/lib/ruby/1.8/webrick/server.rb:82:in `start'
vendor/rails/railties/lib/webrick_server.rb:62:in `dispatch'
vendor/rails/railties/lib/commands/servers/webrick.rb:66
D:/Tools/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
D:/Tools/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in `new_constants_in'
vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
vendor/rails/railties/lib/commands/server.rb:39
D:/Tools/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
D:/Tools/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
script/server:3
```

Rendering D:/Tools/redmine-0.8.5/public/500.html (500 Internal Server Error)

**Comment by wojtha** [comment]
Same here
Redmine 0.8.6.stable.3023
Rails 2.1.2
Windows Vista

**Comment by giemsky** [comment]
Patch that fixes the problem:
http://github.com/gmiklaszewski/redmine-todos-scrum-plugin/commit/61dd31bdcf5713063df744d2e243ca7eef53c267

**Comment by ssteinerx** [comment]
Are these patches applied to the trunk, or is there some other way to get them?  

I made them by hand, but I thought I had pulled the latest from the repository as per installation instructions.

**Comment by giemsky** [comment]
They are applied to my fork.

**Comment by ssteinerx** [comment]
Thanks, got'em!

S

**Comment by kunalashar** [comment]
Thanks, that worked!

**Comment by dalyons** [comment]
yeah, you need rails 2.2.2 or higher.
